In [1]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import numpy as np
import matplotlib.pyplot as plt


In [60]:
t0 = torch.tensor([[1.0, 2, 3], [4,5, 6]])
t1 = torch.transpose(t0, 0, 1)
t1[0, 0] = -1

In [74]:
t0, t1

(tensor([[ 1.,  2.,  3.],
         [ 4., -1.,  6.]]),
 tensor([[-1.,  4.],
         [ 2., -1.],
         [ 3.,  6.]]))

In [76]:
t1=t1.contiguous()
t1[0, 0] = -2
t0, t1

(tensor([[ 1.,  2.,  3.],
         [ 4., -1.,  6.]]),
 tensor([[-2.,  4.],
         [ 2., -1.],
         [ 3.,  6.]]))